# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from low_level/I2C_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class I2C_msg(genpy.Message):
  _md5sum = "90409038824ffc2a00007388b5d017cb"
  _type = "low_level/I2C_msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint16 SharpFrontLeft
uint16 SharpFrontRight
uint16 SharpTop
uint16 KtirBottom
"""
  __slots__ = ['SharpFrontLeft','SharpFrontRight','SharpTop','KtirBottom']
  _slot_types = ['uint16','uint16','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       SharpFrontLeft,SharpFrontRight,SharpTop,KtirBottom

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(I2C_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.SharpFrontLeft is None:
        self.SharpFrontLeft = 0
      if self.SharpFrontRight is None:
        self.SharpFrontRight = 0
      if self.SharpTop is None:
        self.SharpTop = 0
      if self.KtirBottom is None:
        self.KtirBottom = 0
    else:
      self.SharpFrontLeft = 0
      self.SharpFrontRight = 0
      self.SharpTop = 0
      self.KtirBottom = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4H().pack(_x.SharpFrontLeft, _x.SharpFrontRight, _x.SharpTop, _x.KtirBottom))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.SharpFrontLeft, _x.SharpFrontRight, _x.SharpTop, _x.KtirBottom,) = _get_struct_4H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4H().pack(_x.SharpFrontLeft, _x.SharpFrontRight, _x.SharpTop, _x.KtirBottom))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.SharpFrontLeft, _x.SharpFrontRight, _x.SharpTop, _x.KtirBottom,) = _get_struct_4H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4H = None
def _get_struct_4H():
    global _struct_4H
    if _struct_4H is None:
        _struct_4H = struct.Struct("<4H")
    return _struct_4H
