// Generated by gencpp from file low_level/I2C_msg.msg
// DO NOT EDIT!


#ifndef LOW_LEVEL_MESSAGE_I2C_MSG_H
#define LOW_LEVEL_MESSAGE_I2C_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace low_level
{
template <class ContainerAllocator>
struct I2C_msg_
{
  typedef I2C_msg_<ContainerAllocator> Type;

  I2C_msg_()
    : SharpFrontLeft(0)
    , SharpFrontRight(0)
    , SharpTop(0)
    , KtirBottom(0)  {
    }
  I2C_msg_(const ContainerAllocator& _alloc)
    : SharpFrontLeft(0)
    , SharpFrontRight(0)
    , SharpTop(0)
    , KtirBottom(0)  {
  (void)_alloc;
    }



   typedef uint16_t _SharpFrontLeft_type;
  _SharpFrontLeft_type SharpFrontLeft;

   typedef uint16_t _SharpFrontRight_type;
  _SharpFrontRight_type SharpFrontRight;

   typedef uint16_t _SharpTop_type;
  _SharpTop_type SharpTop;

   typedef uint16_t _KtirBottom_type;
  _KtirBottom_type KtirBottom;





  typedef boost::shared_ptr< ::low_level::I2C_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::low_level::I2C_msg_<ContainerAllocator> const> ConstPtr;

}; // struct I2C_msg_

typedef ::low_level::I2C_msg_<std::allocator<void> > I2C_msg;

typedef boost::shared_ptr< ::low_level::I2C_msg > I2C_msgPtr;
typedef boost::shared_ptr< ::low_level::I2C_msg const> I2C_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::low_level::I2C_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::low_level::I2C_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace low_level

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'low_level': ['/home/kdabek/ROSWorkspace/src/low_level/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::low_level::I2C_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::low_level::I2C_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::low_level::I2C_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::low_level::I2C_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::low_level::I2C_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::low_level::I2C_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::low_level::I2C_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90409038824ffc2a00007388b5d017cb";
  }

  static const char* value(const ::low_level::I2C_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90409038824ffc2aULL;
  static const uint64_t static_value2 = 0x00007388b5d017cbULL;
};

template<class ContainerAllocator>
struct DataType< ::low_level::I2C_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "low_level/I2C_msg";
  }

  static const char* value(const ::low_level::I2C_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::low_level::I2C_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 SharpFrontLeft\n\
uint16 SharpFrontRight\n\
uint16 SharpTop\n\
uint16 KtirBottom\n\
";
  }

  static const char* value(const ::low_level::I2C_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::low_level::I2C_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.SharpFrontLeft);
      stream.next(m.SharpFrontRight);
      stream.next(m.SharpTop);
      stream.next(m.KtirBottom);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct I2C_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::low_level::I2C_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::low_level::I2C_msg_<ContainerAllocator>& v)
  {
    s << indent << "SharpFrontLeft: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.SharpFrontLeft);
    s << indent << "SharpFrontRight: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.SharpFrontRight);
    s << indent << "SharpTop: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.SharpTop);
    s << indent << "KtirBottom: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.KtirBottom);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOW_LEVEL_MESSAGE_I2C_MSG_H
