// Generated by gencpp from file low_level/Keyboard_msg.msg
// DO NOT EDIT!


#ifndef LOW_LEVEL_MESSAGE_KEYBOARD_MSG_H
#define LOW_LEVEL_MESSAGE_KEYBOARD_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace low_level
{
template <class ContainerAllocator>
struct Keyboard_msg_
{
  typedef Keyboard_msg_<ContainerAllocator> Type;

  Keyboard_msg_()
    : Command()  {
    }
  Keyboard_msg_(const ContainerAllocator& _alloc)
    : Command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Command_type;
  _Command_type Command;





  typedef boost::shared_ptr< ::low_level::Keyboard_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::low_level::Keyboard_msg_<ContainerAllocator> const> ConstPtr;

}; // struct Keyboard_msg_

typedef ::low_level::Keyboard_msg_<std::allocator<void> > Keyboard_msg;

typedef boost::shared_ptr< ::low_level::Keyboard_msg > Keyboard_msgPtr;
typedef boost::shared_ptr< ::low_level::Keyboard_msg const> Keyboard_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::low_level::Keyboard_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::low_level::Keyboard_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace low_level

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'low_level': ['/home/kdabek/ROSWorkspace/src/low_level/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::low_level::Keyboard_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::low_level::Keyboard_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::low_level::Keyboard_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::low_level::Keyboard_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::low_level::Keyboard_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::low_level::Keyboard_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::low_level::Keyboard_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3e9d1976cb2a74a2f5cb06ef8ad543d";
  }

  static const char* value(const ::low_level::Keyboard_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3e9d1976cb2a74aULL;
  static const uint64_t static_value2 = 0x2f5cb06ef8ad543dULL;
};

template<class ContainerAllocator>
struct DataType< ::low_level::Keyboard_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "low_level/Keyboard_msg";
  }

  static const char* value(const ::low_level::Keyboard_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::low_level::Keyboard_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Command\n\
";
  }

  static const char* value(const ::low_level::Keyboard_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::low_level::Keyboard_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Keyboard_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::low_level::Keyboard_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::low_level::Keyboard_msg_<ContainerAllocator>& v)
  {
    s << indent << "Command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOW_LEVEL_MESSAGE_KEYBOARD_MSG_H
