// Generated by gencpp from file low_level/PWM_msg.msg
// DO NOT EDIT!


#ifndef LOW_LEVEL_MESSAGE_PWM_MSG_H
#define LOW_LEVEL_MESSAGE_PWM_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace low_level
{
template <class ContainerAllocator>
struct PWM_msg_
{
  typedef PWM_msg_<ContainerAllocator> Type;

  PWM_msg_()
    : PWM_on(false)
    , DutyCycle(0)
    , Device()  {
    }
  PWM_msg_(const ContainerAllocator& _alloc)
    : PWM_on(false)
    , DutyCycle(0)
    , Device(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _PWM_on_type;
  _PWM_on_type PWM_on;

   typedef uint8_t _DutyCycle_type;
  _DutyCycle_type DutyCycle;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Device_type;
  _Device_type Device;





  typedef boost::shared_ptr< ::low_level::PWM_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::low_level::PWM_msg_<ContainerAllocator> const> ConstPtr;

}; // struct PWM_msg_

typedef ::low_level::PWM_msg_<std::allocator<void> > PWM_msg;

typedef boost::shared_ptr< ::low_level::PWM_msg > PWM_msgPtr;
typedef boost::shared_ptr< ::low_level::PWM_msg const> PWM_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::low_level::PWM_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::low_level::PWM_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace low_level

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'low_level': ['/home/kdabek/ROSWorkspace/src/low_level/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::low_level::PWM_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::low_level::PWM_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::low_level::PWM_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::low_level::PWM_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::low_level::PWM_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::low_level::PWM_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::low_level::PWM_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2a52dcb9d1729882658bf99403797dd";
  }

  static const char* value(const ::low_level::PWM_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2a52dcb9d172988ULL;
  static const uint64_t static_value2 = 0x2658bf99403797ddULL;
};

template<class ContainerAllocator>
struct DataType< ::low_level::PWM_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "low_level/PWM_msg";
  }

  static const char* value(const ::low_level::PWM_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::low_level::PWM_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool PWM_on\n\
uint8 DutyCycle\n\
string Device\n\
";
  }

  static const char* value(const ::low_level::PWM_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::low_level::PWM_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.PWM_on);
      stream.next(m.DutyCycle);
      stream.next(m.Device);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PWM_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::low_level::PWM_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::low_level::PWM_msg_<ContainerAllocator>& v)
  {
    s << indent << "PWM_on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.PWM_on);
    s << indent << "DutyCycle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.DutyCycle);
    s << indent << "Device: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Device);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOW_LEVEL_MESSAGE_PWM_MSG_H
