// Generated by gencpp from file low_level/TimeServiceRequest.msg
// DO NOT EDIT!


#ifndef LOW_LEVEL_MESSAGE_TIMESERVICEREQUEST_H
#define LOW_LEVEL_MESSAGE_TIMESERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace low_level
{
template <class ContainerAllocator>
struct TimeServiceRequest_
{
  typedef TimeServiceRequest_<ContainerAllocator> Type;

  TimeServiceRequest_()
    : Request()  {
    }
  TimeServiceRequest_(const ContainerAllocator& _alloc)
    : Request(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Request_type;
  _Request_type Request;





  typedef boost::shared_ptr< ::low_level::TimeServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::low_level::TimeServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TimeServiceRequest_

typedef ::low_level::TimeServiceRequest_<std::allocator<void> > TimeServiceRequest;

typedef boost::shared_ptr< ::low_level::TimeServiceRequest > TimeServiceRequestPtr;
typedef boost::shared_ptr< ::low_level::TimeServiceRequest const> TimeServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::low_level::TimeServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::low_level::TimeServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace low_level

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'low_level': ['/home/kdabek/ROSWorkspace/src/low_level/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::low_level::TimeServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::low_level::TimeServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::low_level::TimeServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::low_level::TimeServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::low_level::TimeServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::low_level::TimeServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::low_level::TimeServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9addc784348d4dbc78ae9dca17da0d2";
  }

  static const char* value(const ::low_level::TimeServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9addc784348d4dbULL;
  static const uint64_t static_value2 = 0xc78ae9dca17da0d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::low_level::TimeServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "low_level/TimeServiceRequest";
  }

  static const char* value(const ::low_level::TimeServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::low_level::TimeServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Request\n\
";
  }

  static const char* value(const ::low_level::TimeServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::low_level::TimeServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::low_level::TimeServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::low_level::TimeServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "Request: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOW_LEVEL_MESSAGE_TIMESERVICEREQUEST_H
